import Head from 'next/head'
import Header from '../components/Header';

const Research = () => (
    <div>
        <Head>
            <title>-carly-richardson--portfolio-</title>
            <meta name="portfolio for carly richardson" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
                href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500&family=Source+Sans+Pro&display=swap"
                rel="stylesheet"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Mansalva&family=Source+Sans+Pro&display=swap"
                rel="stylesheet"
            />
        </Head>
        <body className='min-h-screen bg-gradient-to-br from-indigo-900 via-indigo-700 to-indigo-500'>
            <main>
                <Header />
                <h1>Hello</h1>
            </main>
        </body>
    </div >
);

export default Research;